// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.30.0
// 	protoc        v3.14.0
// source: github.com/hyzx-microserver/b2c-common-api/proto/validation.proto

package common

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 通用字段验证规则
type ValidationRules struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Required  bool   `protobuf:"varint,1,opt,name=required,proto3" json:"required,omitempty"`                    // 是否为必填字段
	MaxLength int32  `protobuf:"varint,2,opt,name=max_length,json=maxLength,proto3" json:"max_length,omitempty"` // 最大长度
	MinLength int32  `protobuf:"varint,3,opt,name=min_length,json=minLength,proto3" json:"min_length,omitempty"` // 最小长度
	Pattern   string `protobuf:"bytes,4,opt,name=pattern,proto3" json:"pattern,omitempty"`                       // 正则表达式规则
}

func (x *ValidationRules) Reset() {
	*x = ValidationRules{}
	if protoimpl.UnsafeEnabled {
		mi := &file_github_com_hyzx_microserver_b2c_common_api_proto_validation_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ValidationRules) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ValidationRules) ProtoMessage() {}

func (x *ValidationRules) ProtoReflect() protoreflect.Message {
	mi := &file_github_com_hyzx_microserver_b2c_common_api_proto_validation_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ValidationRules.ProtoReflect.Descriptor instead.
func (*ValidationRules) Descriptor() ([]byte, []int) {
	return file_github_com_hyzx_microserver_b2c_common_api_proto_validation_proto_rawDescGZIP(), []int{0}
}

func (x *ValidationRules) GetRequired() bool {
	if x != nil {
		return x.Required
	}
	return false
}

func (x *ValidationRules) GetMaxLength() int32 {
	if x != nil {
		return x.MaxLength
	}
	return 0
}

func (x *ValidationRules) GetMinLength() int32 {
	if x != nil {
		return x.MinLength
	}
	return 0
}

func (x *ValidationRules) GetPattern() string {
	if x != nil {
		return x.Pattern
	}
	return ""
}

// 验证结果
type ValidationResult struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	IsValid bool   `protobuf:"varint,1,opt,name=is_valid,json=isValid,proto3" json:"is_valid,omitempty"` // 验证是否通过
	Message string `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`                 // 错误信息
}

func (x *ValidationResult) Reset() {
	*x = ValidationResult{}
	if protoimpl.UnsafeEnabled {
		mi := &file_github_com_hyzx_microserver_b2c_common_api_proto_validation_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ValidationResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ValidationResult) ProtoMessage() {}

func (x *ValidationResult) ProtoReflect() protoreflect.Message {
	mi := &file_github_com_hyzx_microserver_b2c_common_api_proto_validation_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ValidationResult.ProtoReflect.Descriptor instead.
func (*ValidationResult) Descriptor() ([]byte, []int) {
	return file_github_com_hyzx_microserver_b2c_common_api_proto_validation_proto_rawDescGZIP(), []int{1}
}

func (x *ValidationResult) GetIsValid() bool {
	if x != nil {
		return x.IsValid
	}
	return false
}

func (x *ValidationResult) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_github_com_hyzx_microserver_b2c_common_api_proto_validation_proto protoreflect.FileDescriptor

var file_github_com_hyzx_microserver_b2c_common_api_proto_validation_proto_rawDesc = []byte{
	0x0a, 0x41, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x68, 0x79, 0x7a,
	0x78, 0x2d, 0x6d, 0x69, 0x63, 0x72, 0x6f, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x2f, 0x62, 0x32,
	0x63, 0x2d, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2d, 0x61, 0x70, 0x69, 0x2f, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x2f, 0x76, 0x61, 0x6c, 0x69, 0x64, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x12, 0x06, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x22, 0x85, 0x01, 0x0a, 0x0f,
	0x56, 0x61, 0x6c, 0x69, 0x64, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x75, 0x6c, 0x65, 0x73, 0x12,
	0x1a, 0x0a, 0x08, 0x72, 0x65, 0x71, 0x75, 0x69, 0x72, 0x65, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x08, 0x52, 0x08, 0x72, 0x65, 0x71, 0x75, 0x69, 0x72, 0x65, 0x64, 0x12, 0x1d, 0x0a, 0x0a, 0x6d,
	0x61, 0x78, 0x5f, 0x6c, 0x65, 0x6e, 0x67, 0x74, 0x68, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52,
	0x09, 0x6d, 0x61, 0x78, 0x4c, 0x65, 0x6e, 0x67, 0x74, 0x68, 0x12, 0x1d, 0x0a, 0x0a, 0x6d, 0x69,
	0x6e, 0x5f, 0x6c, 0x65, 0x6e, 0x67, 0x74, 0x68, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x52, 0x09,
	0x6d, 0x69, 0x6e, 0x4c, 0x65, 0x6e, 0x67, 0x74, 0x68, 0x12, 0x18, 0x0a, 0x07, 0x70, 0x61, 0x74,
	0x74, 0x65, 0x72, 0x6e, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x70, 0x61, 0x74, 0x74,
	0x65, 0x72, 0x6e, 0x22, 0x47, 0x0a, 0x10, 0x56, 0x61, 0x6c, 0x69, 0x64, 0x61, 0x74, 0x69, 0x6f,
	0x6e, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x12, 0x19, 0x0a, 0x08, 0x69, 0x73, 0x5f, 0x76, 0x61,
	0x6c, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x07, 0x69, 0x73, 0x56, 0x61, 0x6c,
	0x69, 0x64, 0x12, 0x18, 0x0a, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x42, 0x40, 0x5a, 0x3e,
	0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x68, 0x79, 0x7a, 0x78, 0x2d,
	0x6d, 0x69, 0x63, 0x72, 0x6f, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x2f, 0x62, 0x32, 0x63, 0x2d,
	0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2d, 0x61, 0x70, 0x69, 0x2f, 0x67, 0x65, 0x6e, 0x65, 0x72,
	0x61, 0x74, 0x65, 0x64, 0x2f, 0x67, 0x6f, 0x2f, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x62, 0x06,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_github_com_hyzx_microserver_b2c_common_api_proto_validation_proto_rawDescOnce sync.Once
	file_github_com_hyzx_microserver_b2c_common_api_proto_validation_proto_rawDescData = file_github_com_hyzx_microserver_b2c_common_api_proto_validation_proto_rawDesc
)

func file_github_com_hyzx_microserver_b2c_common_api_proto_validation_proto_rawDescGZIP() []byte {
	file_github_com_hyzx_microserver_b2c_common_api_proto_validation_proto_rawDescOnce.Do(func() {
		file_github_com_hyzx_microserver_b2c_common_api_proto_validation_proto_rawDescData = protoimpl.X.CompressGZIP(file_github_com_hyzx_microserver_b2c_common_api_proto_validation_proto_rawDescData)
	})
	return file_github_com_hyzx_microserver_b2c_common_api_proto_validation_proto_rawDescData
}

var file_github_com_hyzx_microserver_b2c_common_api_proto_validation_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_github_com_hyzx_microserver_b2c_common_api_proto_validation_proto_goTypes = []interface{}{
	(*ValidationRules)(nil),  // 0: common.ValidationRules
	(*ValidationResult)(nil), // 1: common.ValidationResult
}
var file_github_com_hyzx_microserver_b2c_common_api_proto_validation_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_github_com_hyzx_microserver_b2c_common_api_proto_validation_proto_init() }
func file_github_com_hyzx_microserver_b2c_common_api_proto_validation_proto_init() {
	if File_github_com_hyzx_microserver_b2c_common_api_proto_validation_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_github_com_hyzx_microserver_b2c_common_api_proto_validation_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ValidationRules); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_github_com_hyzx_microserver_b2c_common_api_proto_validation_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ValidationResult); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_github_com_hyzx_microserver_b2c_common_api_proto_validation_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_github_com_hyzx_microserver_b2c_common_api_proto_validation_proto_goTypes,
		DependencyIndexes: file_github_com_hyzx_microserver_b2c_common_api_proto_validation_proto_depIdxs,
		MessageInfos:      file_github_com_hyzx_microserver_b2c_common_api_proto_validation_proto_msgTypes,
	}.Build()
	File_github_com_hyzx_microserver_b2c_common_api_proto_validation_proto = out.File
	file_github_com_hyzx_microserver_b2c_common_api_proto_validation_proto_rawDesc = nil
	file_github_com_hyzx_microserver_b2c_common_api_proto_validation_proto_goTypes = nil
	file_github_com_hyzx_microserver_b2c_common_api_proto_validation_proto_depIdxs = nil
}
